[package]
name = "luks"
version = "0.1.0"
edition = "2024"
description = "Pure-Rust Library for the Linux Unified Key Setup"
repository = "https://github.com/louib/luks-rs"
homepage = "https://github.com/louib/luks-rs"
license = "MIT"

readme = "README.md"

include = [
  "src/",
  "README.md",
  "LICENSE",
]

[dependencies]
